### PR TITLE
Packaging Tweaks

### PR DESCRIPTION
**Pull request by gtjoseph**
* Added armv7hl to list of valid architectures
* Moved creation of SD card directories to common.functions
* The rpm build now also creates srpms.
* Fix systemctl commands in spec files to not try and replace files
  with duetcontrolserver or duetwebserver running.
* Update spec files for .NET Core 3.0.
* Update spec files for inclusion of the IAP binaries.
* Update spec files for new ModelObserver utility.
* Fix typo in pkg/build.sh that was looking for parse_args in
  the wrong place when not run from the pkg directory.

### CODE REVIEW

**Comment by chrishamm** [comment]
Thanks! Just be aware that ARMv6 and older generally isn't supported by .NET Core because it misses some low-level instructions for the used JIT. We will provide a Mono-based builds for ARMv6 at some point but that is still low priority.

**Comment by gtjoseph** [comment]
> Thanks! Just be aware that ARMv6 and older generally isn't supported by .NET Core because it misses some low-level instructions for the used JIT. We will provide a Mono-based builds for ARMv6 at some point but that is still low priority.

Thanks @chrishamm!

@wilriker FYI ^^ since you added armv6h.

**Comment by wilriker** [comment]
I think I also added plain `arm`. But this as well as `armv6h` can be removed again. I just added them for completeness but if .NET Core does not support it it can also be removed again.

**Comment by gtjoseph** [comment]
> I think I also added plain `arm`. But this as well as `armv6h` can be removed again. I just added them for completeness but if .NET Core does not support it it can also be removed again.

I'll remove them the next time I have an update.

**Pull request merged**
