### PR TITLE
Refactor packaging scripts

### PR DESCRIPTION
**Pull request by gtjoseph**
* Created pkg/common pkg/deb pkg/rpm directories.

* Moved non-deb package files to common/<package>.
  Systemd service files, config files, etc.

* Moved deb-specific package files (DEBIAN/*) to deb/<package>.
  control, changelog, etc.

* Split pkg/build.sh into common and deb-specific scripts.
  Running dotnet publish, building DWC, creating sd card,
  etc. are all non-deb-specific things and are now in
  common/common.functions.  Building and signing the deb
  packages are now in deb/build.sh which "sources"
  common.functions.  A similar rpm/build.sh script will
  be created for rpms.

* A new pkg/build.sh was created that will run any or all
  package creation scripts.  For backwards compatibility,
  running pkg/build.sh with no arguments does what it did
  in the past...build debs for armhf in /tmp/duet.
  './build.sh --help' give all the options.

* Added support for building for different target architectures.
  You can pass --target-arch=<arch> to any of the build.sh
  scripts to have dotnet build for that architecture and
  packages created for that architecture.
  Architectures can be i386, i686, x86_64, armhf, armhfp, aarch64.
  The scripts converts them into the proper dotnet RID like
  linux-x86 or linux-arm64.

* Added support for building Debug or Release dotnet assemblies.

* Added support for using a different output directory.

* Added support for building only some packages.

* Added support for building but not packaging.

* Added rpm/build.sh as a placeholder.

### CODE REVIEW

**Comment by gtjoseph** [comment]
Sorry about all the commits.  After all this time, github still doesn't allow you create pull requests that are based on an earlier pull request.  
I'm done for now. :)

**Comment by wilriker** [comment]
You could `git commit --amend` the changes and then force-push it.

I will have a look on Monday if anything needs to be added for Arch Linux packaging. :-)

**Comment by gtjoseph** [comment]
Thanks Manuel.  Feedback appreciated.

I think appending makes things more complicated because it then lumps all the changes together and if you're reviewing you might not know what changed between pushes.  

I work in Gerrit on a daily basis so I guess I'm spoiled. :)

**Comment by wilriker** [comment]
Ohhh Gerrit... Now you sent me back on a memory-journey to a time when everything was better in my (developer) life. :-D

**Comment by wilriker** [comment]
First thing I found is that both `build.sh` and `common.functions` to contain a function `print_help()` but with slightly different contents. Also I will have to adjust a lot of things to make this compatible to Arch Linux packaging. I will get back to you with a patch.

**Comment by wilriker** [comment]
Another thing I just spotted in `common.functions` as that at the top you declare
```sh
RSYNC="rsync -qaH"
```
but then you use it as
```sh
$RSYNC -vaH
```
thus overriding `-q` with `-v`.

**Comment by gtjoseph** [comment]
good catches.  The help in the top level should be the same as the lower level ones except for package types.

**Comment by wilriker** [comment]
And here it comes. This is what is required to use the build script from Arch Linux `PKGBUILD` files.
[0001-Add-PKGBUILD-Arch-Linux-for-packaging.patch.zip](https://github.com/chrishamm/DuetSoftwareFramework/files/3630927/0001-Add-PKGBUILD-Arch-Linux-for-packaging.patch.zip)

**Comment by gtjoseph** [comment]
> And here it comes. This is what is required to use the build script from Arch Linux `PKGBUILD` files.
> [0001-Add-PKGBUILD-Arch-Linux-for-packaging.patch.zip](https://github.com/chrishamm/DuetSoftwareFramework/files/3630927/0001-Add-PKGBUILD-Arch-Linux-for-packaging.patch.zip)

Don't want to include the packaging stuff itself or it is to complicated ?
Also, you're forcing CLEANUP=0 in PKGBUILD/build.sh.  Is this intentional?

**Comment by wilriker** [comment]
Hi George,
Yeah, packaging on Arch Linux works a bit different. I am not exactly sure how it works for the official repos but in the AUR (Arch User Repository) any user can upload any package - though not as a fully packages just-extract-me-the-right-way-package but only as a package description file `PKGBUILD` ([example](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=duetcontrolserver-bin) of currently submitted `duetcontrolserver-bin`) this will then contain all instructions of what to do. In best case this will only have to run
```
make
make PREFIX="${pkgdir}" install
```
apart from the automated stuff of downloading and unpacking, etc.

So, all I need from `build.sh` is to build everything (perfect would be even if all the `progs` could be built separately) and then I have to move/copy all files to the place `makepkg` expects them (since you hard-coded several path elements into the `--dest-dir` unfortunately I cannot use this directly). And that's also why cleaning must not happen since after `build.sh` finished I need to copy over the built results.

**Comment by gtjoseph** [comment]
Gotcha.  I'll merge in your patch into this pull request in a bit.

**Comment by gtjoseph** [comment]
@chrishamm Any chance of getting this merged in this weekend?

**Comment by chrishamm** [comment]
Yes, I will have a look at it today in the evening. I still need to update the package files anyway so I can combine that with your PR. Thanks for your contribution!

**Comment by chrishamm** [comment]
I cannot comment on the RPM build scripts but while reviewing them I saw some runtime libs seem to be hardcoded in the .spec files. Just a word of warning: They're expected to change quite soon due to the planned upgrade to .NET Core 3 and I won't explicitly maintain them. Perhaps it would be better to update them dynamically?

In principle I don't see any issues hosting RPMs and Arch packages too, but I don't have a lot of experience with repos for both other package systems. Any thoughts?

**Comment by gtjoseph** [comment]
Thanks @chrishamm !

> I cannot comment on the RPM build scripts but while reviewing them I saw some runtime libs seem to be hardcoded in the .spec files. Just a word of warning: They're expected to change quite soon due to the planned upgrade to .NET Core 3 and I won't explicitly maintain them. Perhaps it would be better to update them dynamically?
> 

Yeah good point.  I'll fix them.

> In principle I don't see any issues hosting RPMs and Arch packages too, but I don't have a lot of experience with repos for both other package systems. Any thoughts?

I think the Arch and RPM packages are niche enough that you don't have to host them for now.  Arch has the AUR community repos and Fedora/CentOS has the COPR equivalent. I think @wilriker and I can take care of those for now.  One thing that'd help us is tagging each release though.

You could build and host arm64 builds for deb though.  That will probably be the most common distribution after armhf.

**Comment by wilriker** [comment]
As @gtjoseph said Arch and RPM are rather niche. Additionally for Arch it is rather uncommon to have precompiled package repos other than the official ones.

But yes, a way to get actively notified of a new version would be great.

**Pull request merged**
